# Hidden Markov Model

This notebook contains the code displaying the results for a Hidden Markov Model (HMM) built using the NumPy library. 

The code in `hmm.py` aims to address the three fundamental problems of HMMs: 

1. **Likelihood:** Compute the likelihood of a given observation sequence.
2. **Decoding:** Determine the most likely hidden state sequence for a given observation sequence.
3. **Learning:** Learn the HMM parameters given an observation sequence.

In [1]:
# imports
import numpy as np
from hmm import HiddenMarkovModel

### Build the model

In [2]:
# initialize model parameters
state_space = ["hot", "cold"]
observation_space = [1, 2, 3]  ### Q
initial_probabilities = [0.8, 0.2] ### pi
transition_probabilities = [[0.6, 0.4], [0.5, 0.5]]  ### A
emission_probabilities = [[0.2, 0.4, 0.4], [0.5, 0.4, 0.1]]    ##b

In [3]:
# build model
hmm = HiddenMarkovModel(state_space, observation_space, transition_probabilities, 
                        emission_probabilities, initial_probabilities)

### Problem 1: Likelihood

Given an HMM $\lambda = (A, B, \pi)$ and an observation sequence $O$, determine the likelihood $P(O|\lambda)$.

In [28]:
# calculate likelihood
observation_sequence = [1, 2, 3, 2, 2, 1, 2]
likelihood = hmm.likelihood(observation_sequence)
print("* Observation sequence: {}".format(observation_sequence))
print("* Likelihood: {:.2e}".format(likelihood))

* Observation sequence: [1, 2, 3, 2, 2, 1, 2]
* Likelihood: 5.92e-04


### Problem 2: Decoding

Given an observation sequence $O$ and an HMM $\lambda = (A, B, \pi)$, discover the best hidden state sequence $Q$.

In [42]:
# determine most likely state sequence
path, prob = hmm.decode(observation_sequence)
print("* Observation sequence: {}".format(observation_sequence))
print("* Most likely hidden state path: {}".format(path))
print("* Likelihood for observation sequence along path: {:.2e}".format(prob))

* Observation sequence: [1, 2, 3, 2, 2, 1, 2]
* Most likely hidden state path: ['cold' 'hot' 'hot' 'hot' 'hot' 'cold' 'hot']
* Likelihood for observation sequence along path: 4.77e-04


### Problem 3: Learning

Given an observation sequence $O$ and the set of states in the HMM, learn the HMM parameters $A$, $B$, and $\pi$.

In [31]:
# print original parameters
print("PROBABILITIES BEFORE LEARNING")
print("-----------------------------")
print("* Initial:")
print(hmm.pi)
print("\n* Transition:")
print(hmm.tp)
print("\n* Emission:")
print(hmm.ep)

PROBABILITIES BEFORE LEARNING
-----------------------------
* Initial:
[0.8 0.2]

* Transition:
[[0.6 0.4]
 [0.5 0.5]]

* Emission:
[[0.2 0.4 0.4]
 [0.5 0.4 0.1]]


In [40]:
# learn from observation sequence
hmm.learn(observation_sequence, iterations=1)

In [41]:
# print parameters after learning
print("PROBABILITIES AFTER LEARNING")
print("----------------------------")
print("* Initial:")
print(hmm.pi)
print("\n* Transition:")
print(hmm.tp)
print("\n* Emission:")
print(hmm.ep)

PROBABILITIES AFTER LEARNING
----------------------------
* Initial:
[0.0865826 0.9134174]

* Transition:
[[0.69703429 0.30296571]
 [0.65405325 0.34594675]]

* Emission:
[[0.11874366 0.6656835  0.21557284]
 [0.53033539 0.43333995 0.03632467]]
