#**Homework 3 : Hidden Markov Model (HMM)**
Author : **raphael** ING5 Promo 

In the below program, both evaluation and decoding problem algorithms have been implemented in one cell

In [3]:
import numpy as np

#Given data
N=3 #number of hidden states
T=4 #time to t=0 to t=4
K = [1, 3, 2, 0] #observable state X=(X1,X3,X2,X0) for X=(X(t=1),X(t=2),X(t=3),X(t=4)) given in the subject

#transition probabilities matrix
a_ij =  np.array([[1,   0,   0,   0],
                [0.2, 0.3, 0.1, 0.4],
                [0.2, 0.5, 0.2, 0.1],
                [0.7, 0.1, 0.1, 0.1]] ) 

#emission probabilities matrix
b_jk = np.array([[1,  0,  0,   0,    0],
                [0, 0.3, 0.4, 0.1, 0.2],
                [0, 0.1, 0.1, 0.7, 0.1],
                [0, 0.5, 0.2, 0.1, 0.2]] )

#matrix of the probabilities that a given sequence of observable states x is generated from a HMM
alpha = np.zeros((N+1,T+1))


##STARTING FORWARD ALGORITHM

#Initializing alpha_j(t=0)
for j in range(N+1):
    if (j==1):
        alpha[j][0] = 1
    else:
        alpha[j][0] = 0

##STARTING DECODING PROBLEM
Path = []
j_prime = np.argmax(alpha[:,0])
Path.append("z"+str(j_prime))

for t in range(1,T+1):
    for j in range(0,N+1):
        alpha_jt = 0
        for i in range(1,N+1):
            alpha_jt += alpha[i][t-1]*a_ij[i][j]*b_jk[j][K[t-1]]
        alpha[j][t] = alpha_jt
    ##END OF FORWARD ALGORITHM

    #Decoding part   
    j_prime = np.argmax(alpha[:,t])
    Path.append("z"+str(j_prime)) #add hidden state to Path
    ##END OF DECODING ALGORITHM   
        

    
print("b_jk :\n", b_jk)
print("\na_ij :\n", a_ij)
print("\nalpha :\n",alpha)
print("\nPath :\n", Path)

b_jk :
 [[1.  0.  0.  0.  0. ]
 [0.  0.3 0.4 0.1 0.2]
 [0.  0.1 0.1 0.7 0.1]
 [0.  0.5 0.2 0.1 0.2]]

a_ij :
 [[1.  0.  0.  0. ]
 [0.2 0.3 0.1 0.4]
 [0.2 0.5 0.2 0.1]
 [0.7 0.1 0.1 0.1]]

alpha :
 [[0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.8218e-03]
 [1.0000e+00 9.0000e-02 5.2000e-03 5.1920e-03 0.0000e+00]
 [0.0000e+00 1.0000e-02 2.1700e-02 5.4300e-04 0.0000e+00]
 [0.0000e+00 2.0000e-01 5.7000e-03 9.6400e-04 0.0000e+00]]

Path :
 ['z1', 'z3', 'z2', 'z1', 'z0']
