In [3]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [6]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [20]:
vectorizer.get_feature_names_out()
print(X.toarray())
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [18]:
print(X2.toarray())

[[0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0
  0 1 1 1 0 0 0 0]
 [0 0 0 0 2 1 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 1 1
  1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0
  0 1 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 1 1 1]]


In [3]:
# Random-text-generator
#Python Script for text generation
import random
import string

vowels='aeiouy'
consonants='bcdfghjklmnpqrstvwxz'
letters=vowels+consonants

letter_input = []
length_input = int(input("Enter the length of inputs you want: "))

for i in range(length_input):
    letter_input.append(input("What letter do you want? Enter 'v' for vowels, 'c' for consonants, 'l' for any letter:"))

def generate():
    name = ""
    for i in range(length_input):
        letter_input_1 = letter_input[i]
        l1 = letter_input_1
        if letter_input_1 == 'v':
            l1=random.choice(vowels)
        elif letter_input_1 == 'c':
            l1=random.choice(consonants)
        elif letter_input_1 == 'l':
            l1=random.choice(letters)
        name=name + l1
    return name

for i in range(20):
    n=generate()
    print(n)

iio
uia
iiu
oio
iie
eia
yio
aie
iiu
oiy
yio
eia
eiu
yiy
iie
oiu
aia
uie
iie
eiy
